#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)
library(bcrypt)

# Define UI for application that draws a histogram
ui <- fluidPage(
   
   # Application title
   titlePanel("Shiny User Authentication Example"),
   
   uiOutput("mainUI")
   
)

# Define server logic required to draw a histogram
server <- function(input, output) {
  
  # The expected username and password are admin/admin
  # The long password string in the following variable is generated by hashpw("admin")
  credentials <- reactiveValues(userIsAuth = FALSE, username = "admin",
                                password = "$2a$12$jxoOXWVRB0XPJzfyViVjY.NkgqZlCcW4UbnOjRPvppH0ENRlH8s3y")
  
  observeEvent(input$loginbtn, {
    if(input$username == credentials$username)
    {
      credentials$userIsAuth <<- checkpw(input$password, credentials$password)
    }
    else
    {
      showModal(modalDialog(
        title = "Error",
        "Incorrect username or password. please try again! (Hint: admin/admin)"
      ))
    }
  })
  
  output$mainUI <- renderUI({
    if(credentials$userIsAuth){
      # Sidebar with a slider input for number of bins 
      sidebarLayout(
        uiOutput("sliderInput"),
        
        # Show a plot of the generated distribution
        mainPanel(
          plotOutput("distPlot")
        )
      )
    }else{
      div(
        div(class = "fill-bg cover-BG"),
        div(
          class = "container-fluid",
          style = "width: 100%;",
          fluidRow(
            div(
              class = "col-md-3 col-sm-4 col-xs-12 col-md-offset-1",
              div(
                id = "login",
                img(
                  class = "img-responsive",
                  style = "margin-bottom:30px"
                ),
                textInput("username", "Username:", width = "100%"),
                passwordInput("password", "Password:", width = "100%"),
                actionButton("loginbtn", "Login", class = "btn-primary full-width")
              )
            )
          )
        )
      )
    }
  })
  
  output$sliderInput <- renderUI({
    sidebarPanel(
      sliderInput("bins",
                  "Number of bins:",
                  min = 1,
                  max = 50,
                  value = 30)
    )
  })
  
  output$distPlot <- renderPlot({
    req(input$bins)
    # generate bins based on input$bins from ui.R
    x    <- faithful[, 2] 
    bins <- seq(min(x), max(x), length.out = input$bins + 1)
    
    # draw the histogram with the specified number of bins
    hist(x, breaks = bins, col = 'darkgray', border = 'white')
  })
  
   
}

# Run the application 
shinyApp(ui = ui, server = server)

